#!/usr/bin/env python3
"""Non-interactive wiki scaffolding, extracted from setup.sh.

Creates, for either tool mode:
- the pages directory and the initial pages rendered from templates/
  (Schema, Dashboard, one Hub per namespace, the Access-Log page)
- the source-pipeline scaffold: raw/ and ingested/<type>/ with .gitkeep
- the tool-specific .gitignore (unless --no-gitignore)
- llm-wiki.yml (unless --no-config; existing config is kept unless
  --overwrite-config)

It does NOT run git init or git commit; that stays in setup.sh.

Existing pages are never overwritten; they are skipped with a warning
(specs/setup.md REQ-786), which yields exit code 1.

Exit codes: 0 = clean, 1 = warnings, 2 = critical.
"""

import argparse
import datetime
import os
import re
import sys

import wikilib

NAMESPACE_RE = re.compile(r"^[A-Za-z][A-Za-z0-9-]*$")

# Stamped on every scaffolded page so fresh pages are NOT grandfathered by
# lint. Must match SCHEMA_SPEC_VERSION in lint.py and both Schema templates
# (check_canon.py verifies those surfaces).
SCHEMA_SPEC_VERSION = "2.0.0"

GITIGNORE = {
    "logseq": """logseq/bak/
logseq/.recycle/
.DS_Store
.logseq/
# Source-pipeline binaries. Provenance is the .md notes in ingested/, not the
# PDFs themselves. Uncomment the next two lines to keep heavy binaries out of git
# history. For a reproducibility setup where the PDFs MUST be versioned, leave
# them commented and instead run: git lfs track "*.pdf"
# raw/**/*.pdf
# ingested/**/*.pdf
""",
    "obsidian": """.obsidian/workspace.json
.obsidian/workspace-mobile.json
.DS_Store
.trash/
# Source-pipeline binaries. Provenance is the .md notes in ingested/, not the
# PDFs themselves. Uncomment the next two lines to keep heavy binaries out of git
# history. For a reproducibility setup where the PDFs MUST be versioned, leave
# them commented and instead run: git lfs track "*.pdf"
# raw/**/*.pdf
# ingested/**/*.pdf
""",
}

CONFIG_TEMPLATE = """# llm-wiki configuration
# Generated by init_wiki.py on {date}

tool: {tool}
wiki_path: {wiki_path}
pages_dir: {pages_dir}
memory_path: {memory_path}

namespaces:
{namespace_lines}
# Source pipeline: drop sources in raw/, ingest synthesises them into pages,
# then the source file is moved into ingested/<type>/. The move is the
# provenance record (in raw/ = pending, in ingested/ = processed).
raw_dir: raw
ingested_dir: ingested
source_types:
{source_type_lines}
default_source_type: papers
"""


class Scaffold:
    def __init__(self):
        self.created = []
        self.skipped = []
        self.quiet = False

    def note(self, message):
        if not self.quiet:
            print(message)

    def write_file(self, path, content, label=None):
        """Create a file; never overwrite. Returns True if written."""
        label = label or os.path.basename(path)
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        if os.path.exists(path):
            self.skipped.append(label)
            self.note("  Skipped (already exists): %s" % label)
            return False
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        self.created.append(label)
        self.note("  Created: %s" % label)
        return True


def read_template(template_dir, name):
    with open(os.path.join(template_dir, name), encoding="utf-8") as handle:
        return handle.read()


def stamp_schema_version(content, tool):
    """Ensure the page carries `schema-spec-version` (correct syntax per mode).

    Every page init_wiki.py scaffolds conforms to the current schema, so it
    gets the stamp; pages without it are treated as pre-2.0.0 by lint
    (grandfather mode). Templates that already carry the property (the
    Schema page) are left untouched.
    """
    if "schema-spec-version" in content:
        return content
    if tool == "logseq":
        return "- schema-spec-version:: %s\n%s" % (SCHEMA_SPEC_VERSION,
                                                   content)
    lines = content.splitlines(True)
    if lines and lines[0].strip() == "---":
        lines.insert(1, 'schema-spec-version: "%s"\n' % SCHEMA_SPEC_VERSION)
        return "".join(lines)
    return '---\nschema-spec-version: "%s"\n---\n%s' % (SCHEMA_SPEC_VERSION,
                                                        content)


def render_pages(scaffold, tool, wiki_path, pages_path, template_dir,
                 namespaces, today):
    """Page creation, ported from the python heredoc in setup.sh Step 8."""
    ns_list = ", ".join("Wiki/%s" % ns for ns in namespaces)
    schema = read_template(template_dir, "Schema.md")
    schema = schema.replace("{{NAMESPACES}}", ns_list)
    schema = schema.replace("{{DATE}}", today)

    dashboard = read_template(template_dir, "Dashboard.md")
    dashboard = dashboard.replace("{{DATE}}", today)

    hub_tpl = read_template(template_dir, "Hub.md")
    access_log = read_template(template_dir, "Access-Log.md")
    access_log = access_log.replace("{{DATE}}", today)

    if tool == "logseq":
        ns_links = "\n".join("\t- [[Wiki/%s]]" % ns for ns in namespaces)
        dashboard = dashboard.replace("{{NAMESPACE_LINKS}}", ns_links)

        scaffold.write_file(os.path.join(pages_path, "Wiki___Schema.md"),
                            stamp_schema_version(schema, tool), "Wiki/Schema")
        scaffold.write_file(os.path.join(pages_path, "Wiki___Dashboard.md"),
                            stamp_schema_version(dashboard, tool),
                            "Wiki/Dashboard")
        for ns in namespaces:
            hub = hub_tpl.replace("{{NAMESPACE}}", ns).replace("{{DATE}}", today)
            scaffold.write_file(os.path.join(pages_path, "Wiki___%s.md" % ns),
                                stamp_schema_version(hub, tool),
                                "Wiki/%s" % ns)
        scaffold.write_file(
            os.path.join(pages_path, "Wiki___Reference___Access-Log.md"),
            stamp_schema_version(access_log, tool),
            "Wiki/Reference/Access-Log")
    else:
        wiki_dir = os.path.join(wiki_path, "Wiki")
        ns_links = "\n".join("- [[Wiki/%s]]" % ns for ns in namespaces)
        dashboard = dashboard.replace("{{NAMESPACE_LINKS}}", ns_links)

        scaffold.write_file(os.path.join(wiki_dir, "Schema.md"),
                            stamp_schema_version(schema, tool),
                            "Wiki/Schema.md")
        scaffold.write_file(os.path.join(wiki_dir, "Dashboard.md"),
                            stamp_schema_version(dashboard, tool),
                            "Wiki/Dashboard.md")
        for ns in namespaces:
            hub = hub_tpl.replace("{{NAMESPACE}}", ns).replace("{{DATE}}", today)
            scaffold.write_file(os.path.join(wiki_dir, ns, "_index.md"),
                                stamp_schema_version(hub, tool),
                                "Wiki/%s/_index.md" % ns)
        scaffold.write_file(
            os.path.join(wiki_dir, "Reference", "Access-Log.md"),
            stamp_schema_version(access_log, tool),
            "Wiki/Reference/Access-Log.md")


def scaffold_pipeline(scaffold, wiki_path):
    """raw/ and ingested/<type>/ beside the pages dir, with .gitkeep files."""
    dirs = [os.path.join(wiki_path, "raw")]
    dirs += [os.path.join(wiki_path, "ingested", t)
             for t in wikilib.DEFAULT_SOURCE_TYPES]
    for directory in dirs:
        os.makedirs(directory, exist_ok=True)
        if not os.listdir(directory):
            gitkeep = os.path.join(directory, ".gitkeep")
            with open(gitkeep, "w", encoding="utf-8"):
                pass
            scaffold.created.append(os.path.relpath(gitkeep, wiki_path))
    scaffold.note("  Scaffolded: raw/ and ingested/{%s}/"
                  % ",".join(wikilib.DEFAULT_SOURCE_TYPES))


def build_config(tool, wiki_path, pages_dir, memory_path, namespaces, today):
    text = CONFIG_TEMPLATE.format(
        date=today,
        tool=tool,
        wiki_path=wiki_path,
        pages_dir=pages_dir,
        memory_path=memory_path,
        namespace_lines="\n".join("  - %s" % ns for ns in namespaces),
        source_type_lines="\n".join("  - %s" % t
                                    for t in wikilib.DEFAULT_SOURCE_TYPES),
    )
    return "\n".join(line.rstrip() for line in text.splitlines()) + "\n"


def default_templates_dir(tool):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
    return os.path.join(repo_root, "templates", tool)


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold an llm-wiki vault (non-interactive)."
    )
    parser.add_argument("--wiki-path", required=True,
                        help="wiki/vault root directory (created if missing)")
    parser.add_argument("--tool", required=True,
                        help="note-taking tool: logseq or obsidian")
    parser.add_argument("--namespaces", nargs="+",
                        default=list(wikilib.DEFAULT_NAMESPACES),
                        help="namespace names (default: %s)"
                             % " ".join(wikilib.DEFAULT_NAMESPACES))
    parser.add_argument("--memory-path", default="",
                        help="Claude Code memory directory (optional)")
    parser.add_argument("--templates-dir", default=None,
                        help="template directory (default: the repo's "
                             "templates/<tool>/)")
    parser.add_argument("--date", default=None,
                        help="date stamp YYYY-MM-DD (default: today)")
    parser.add_argument("--no-gitignore", action="store_true",
                        help="do not write .gitignore")
    parser.add_argument("--no-config", action="store_true",
                        help="do not write llm-wiki.yml")
    parser.add_argument("--overwrite-config", action="store_true",
                        help="overwrite an existing llm-wiki.yml")
    parser.add_argument("--json", action="store_true",
                        help="emit machine-readable JSON")
    args = parser.parse_args()

    scaffold = Scaffold()
    scaffold.quiet = args.json

    if args.tool not in wikilib.VALID_TOOLS:
        message = ("Invalid tool '%s'. Must be 'logseq' or 'obsidian'."
                   % args.tool)
        if args.json:
            wikilib.emit_json({"status": "critical", "criticals": [message]})
        else:
            print("CRITICAL: %s" % message, file=sys.stderr)
        return wikilib.EXIT_CRITICAL

    for ns in args.namespaces:
        if not NAMESPACE_RE.match(ns):
            message = ("Invalid namespace name: '%s'. Namespace names must "
                       "start with a letter and contain only letters, "
                       "numbers, and hyphens." % ns)
            if args.json:
                wikilib.emit_json({"status": "critical",
                                   "criticals": [message]})
            else:
                print("CRITICAL: %s" % message, file=sys.stderr)
            return wikilib.EXIT_CRITICAL

    template_dir = args.templates_dir or default_templates_dir(args.tool)
    if not os.path.isdir(template_dir):
        message = ("Templates not found at %s. Pass --templates-dir or run "
                   "from a checkout of the llm-wiki repository."
                   % template_dir)
        if args.json:
            wikilib.emit_json({"status": "critical", "criticals": [message]})
        else:
            print("CRITICAL: %s" % message, file=sys.stderr)
        return wikilib.EXIT_CRITICAL

    wiki_path = os.path.abspath(wikilib.expand_path(args.wiki_path))
    memory_path = wikilib.expand_path(args.memory_path)
    pages_dir = "pages" if args.tool == "logseq" else ""
    pages_path = os.path.join(wiki_path, pages_dir) if pages_dir else wiki_path
    today = args.date or datetime.date.today().isoformat()

    os.makedirs(pages_path, exist_ok=True)

    scaffold.note("Creating wiki pages...")
    render_pages(scaffold, args.tool, wiki_path, pages_path, template_dir,
                 args.namespaces, today)

    scaffold.note("Scaffolding source pipeline (raw/ + ingested/)...")
    scaffold_pipeline(scaffold, wiki_path)

    if not args.no_gitignore:
        scaffold.write_file(os.path.join(wiki_path, ".gitignore"),
                            GITIGNORE[args.tool], ".gitignore")

    config_path = os.path.join(wiki_path, wikilib.CONFIG_FILENAME)
    if not args.no_config:
        content = build_config(args.tool, wiki_path, pages_dir, memory_path,
                               args.namespaces, today)
        if os.path.exists(config_path) and args.overwrite_config:
            os.remove(config_path)
        scaffold.write_file(config_path, content, wikilib.CONFIG_FILENAME)

    status, exit_code = wikilib.status_from_counts([], scaffold.skipped)
    if args.json:
        wikilib.emit_json({
            "status": status,
            "tool": args.tool,
            "wiki_path": wiki_path,
            "config_path": config_path if not args.no_config else None,
            "created": scaffold.created,
            "skipped": scaffold.skipped,
        })
    else:
        scaffold.note("Done. Wiki at: %s" % wiki_path)
        if scaffold.skipped:
            scaffold.note("Skipped %d existing file(s); nothing was "
                          "overwritten." % len(scaffold.skipped))
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
