#!/usr/bin/env python3
"""build_doc_indexes.py - generate the website's reference index pages.

Quarto pre-render step for the documentation site (_quarto.yml). Builds
the pkgdown-style index pages from sources that already carry the needed
metadata, so the indexes can never drift from the content:

- index.md            copy of README.md (the site homepage)
- reference/skills.md   one row per skills/*/SKILL.md (frontmatter name +
                        first sentence of description), with a link to the
                        skill's plain/ page when one exists
- reference/plain-language.md  one row per plain/*.md (frontmatter title +
                        first sentence of description), linking back to the
                        matching SKILL.md; a skill without a plain page (or
                        a plain page without a skill) is warned on stderr
- reference/specs.md    one row per openspec/specs/*.md (h1 + first
                        Description line)
- reference/articles.md one row per docs/*.md (h1)

All outputs are generated at build time and gitignored; edit the sources,
not these files. Stdlib only (the YAML frontmatter of skills
is single-line key: value, parsed with a mini-reader, no pyyaml).
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GENERATED_NOTE = ("<!-- GENERATED by tools/build_doc_indexes.py "
                  "(quarto pre-render); edit the sources, not this file -->")


def read(path):
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def write(rel, text):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("build_doc_indexes: wrote %s" % rel)


def frontmatter(text):
    """Single-line `key: value` pairs between --- fences. A folded or
    literal block scalar (`key: >-` etc.) is joined into one line."""
    if not text.startswith("---"):
        return {}
    body = text.split("---", 2)
    if len(body) < 3:
        return {}
    fields = {}
    lines = body[1].splitlines()
    i = 0
    while i < len(lines):
        match = re.match(r"^([A-Za-z][\w-]*):\s*(.*)$", lines[i])
        i += 1
        if not match:
            continue
        value = match.group(2).strip()
        if value in (">", ">-", ">+", "|", "|-", "|+"):
            block = []
            while i < len(lines) and (not lines[i].strip()
                                      or lines[i].startswith(" ")):
                block.append(lines[i].strip())
                i += 1
            value = " ".join(part for part in block if part)
        if value:
            fields[match.group(1)] = value
    return fields


def first_sentence(text):
    match = re.match(r"(.+?\.)\s", text + " ")
    return match.group(1) if match else text


def first_h1(text):
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def escape_cell(text):
    return text.replace("|", "\\|")


def page(title, description, rows_header, rows):
    columns = len(rows_header.strip().strip("|").split("|"))
    separator = "|" + "|".join(["---"] * columns) + "|"
    lines = ["---", "title: %s" % title, "---", "", GENERATED_NOTE, "",
             description, "", rows_header, separator]
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines)


def skill_names():
    skills_dir = os.path.join(ROOT, "skills")
    return [name for name in sorted(os.listdir(skills_dir))
            if os.path.isfile(os.path.join(skills_dir, name, "SKILL.md"))]


def has_plain_page(name):
    return os.path.isfile(os.path.join(ROOT, "plain", "%s.md" % name))


def build_skills():
    rows = []
    for name in skill_names():
        meta = frontmatter(read(
            os.path.join(ROOT, "skills", name, "SKILL.md")))
        if has_plain_page(name):
            plain_cell = "[in plain language](../plain/%s.md)" % name
        else:
            plain_cell = ""
            print("build_doc_indexes: WARNING skills/%s has no "
                  "plain/%s.md page" % (name, name), file=sys.stderr)
        rows.append("| [%s](../skills/%s/SKILL.md) | %s | %s |" % (
            meta.get("name", name), name,
            escape_cell(first_sentence(meta.get("description", ""))),
            plain_cell))
    write("reference/skills.md", page(
        "Skills", "The skill suite, one entry per installed skill. Every "
        "skill has two pages. The page in the Skill column is the skill's "
        "own SKILL.md, the instructions the model runs, published word for "
        "word. The page in the last column explains the same skill in "
        "plain language, written for people.",
        "| Skill | Description | Plain language |", rows))


def build_skills_plain():
    rows = []
    names = skill_names()
    plain_dir = os.path.join(ROOT, "plain")
    filenames = sorted(os.listdir(plain_dir)) if os.path.isdir(
        plain_dir) else []
    for filename in filenames:
        if not filename.endswith(".md"):
            continue
        name = filename[:-3]
        if name not in names:
            print("build_doc_indexes: WARNING plain/%s matches no "
                  "skills/%s/SKILL.md" % (filename, name), file=sys.stderr)
        meta = frontmatter(read(os.path.join(plain_dir, filename)))
        rows.append("| [%s](../plain/%s) | %s | [SKILL.md](../skills/%s/SKILL.md) |" % (
            name, filename,
            escape_cell(first_sentence(meta.get("description", ""))),
            name))
    # Not "skills-plain.md": Quarto reserves <stem>-plain.md as the markdown
    # engine's intermediate name for an input <stem>.md and silently drops
    # such files from the project inputs, so that name would never render.
    write("reference/plain-language.md", page(
        "Skills in plain language",
        "Every skill explained in plain language, one page per skill. "
        "The pages in the Skill column are written for people. The last "
        "column links the standard page, the exact instructions the model "
        "runs.",
        "| Skill | What it does | Standard page |", rows))


def build_specs():
    rows = []
    specs_dir = os.path.join(ROOT, "openspec", "specs")
    for filename in sorted(os.listdir(specs_dir)):
        if not filename.endswith(".md"):
            continue
        text = read(os.path.join(specs_dir, filename))
        title = first_h1(text) or filename
        title = re.sub(r"^Spec:\s*", "", title)
        description = ""
        match = re.search(r"## Description\n+((?:[^\n]+\n)+)", text)
        if match:
            description = " ".join(match.group(1).split())
        rows.append("| [%s](../openspec/specs/%s) | %s |" % (
            escape_cell(title), filename,
            escape_cell(first_sentence(description))))
    write("reference/specs.md", page(
        "Specs", "The spec canon (`openspec/specs/`): the normative "
        "requirements every skill, script, and template surface must "
        "agree with (`check_canon.py` enforces the agreement).",
        "| Spec | Description |", rows))


def build_articles():
    rows = []
    docs_dir = os.path.join(ROOT, "docs")
    for filename in sorted(os.listdir(docs_dir)):
        if not filename.endswith(".md"):
            continue
        title = first_h1(read(os.path.join(docs_dir, filename))) or filename
        rows.append("| [%s](../docs/%s) |" % (escape_cell(title), filename))
    write("reference/articles.md", page(
        "Articles", "Guides and workflow documentation from `docs/`.",
        "| Article |", rows))


def build_home():
    write("index.md", GENERATED_NOTE + "\n\n" + read(
        os.path.join(ROOT, "README.md")))


def main():
    build_home()
    build_skills()
    build_skills_plain()
    build_specs()
    build_articles()
    return 0


if __name__ == "__main__":
    sys.exit(main())
