#!/usr/bin/env python3
"""build_doc_indexes.py - generate the website's reference index pages.

Quarto pre-render step for the documentation site (_quarto.yml). Builds
the pkgdown-style index pages from sources that already carry the needed
metadata, so the indexes can never drift from the content:

- index.md            copy of README.md (the site homepage)
- reference/skills.md   one row per skills/*/SKILL.md (frontmatter name +
                        first sentence of description)
- reference/agents.md   one row per agents/*.md (frontmatter name, model,
                        first sentence of description)
- reference/specs.md    one row per openspec/specs/*.md (h1 + first
                        Description line)
- reference/articles.md one row per docs/*.md (h1)

All outputs are generated at build time and gitignored; edit the sources,
not these files. Stdlib only (the YAML frontmatter of skills and agents
is single-line key: value, parsed with a mini-reader, no pyyaml).
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GENERATED_NOTE = ("<!-- GENERATED by tools/build_doc_indexes.py "
                  "(quarto pre-render); edit the sources, not this file -->")


def read(path):
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def write(rel, text):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("build_doc_indexes: wrote %s" % rel)


def frontmatter(text):
    """Single-line `key: value` pairs between --- fences."""
    if not text.startswith("---"):
        return {}
    body = text.split("---", 2)
    if len(body) < 3:
        return {}
    fields = {}
    for line in body[1].splitlines():
        match = re.match(r"^([A-Za-z][\w-]*):\s*(.+)$", line)
        if match:
            fields[match.group(1)] = match.group(2).strip()
    return fields


def first_sentence(text):
    match = re.match(r"(.+?\.)\s", text + " ")
    return match.group(1) if match else text


def first_h1(text):
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def escape_cell(text):
    return text.replace("|", "\\|")


def page(title, description, rows_header, rows):
    columns = len(rows_header.strip().strip("|").split("|"))
    separator = "|" + "|".join(["---"] * columns) + "|"
    lines = ["---", "title: %s" % title, "---", "", GENERATED_NOTE, "",
             description, "", rows_header, separator]
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines)


def build_skills():
    rows = []
    skills_dir = os.path.join(ROOT, "skills")
    for name in sorted(os.listdir(skills_dir)):
        skill_md = os.path.join(skills_dir, name, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        meta = frontmatter(read(skill_md))
        rows.append("| [%s](../skills/%s/SKILL.md) | %s |" % (
            meta.get("name", name), name,
            escape_cell(first_sentence(meta.get("description", "")))))
    write("reference/skills.md", page(
        "Skills", "The skill suite, one entry per installed skill. Each "
        "page is the skill's own SKILL.md: the instructions the model "
        "executes, published verbatim.",
        "| Skill | Description |", rows))


def build_agents():
    rows = []
    agents_dir = os.path.join(ROOT, "agents")
    for filename in sorted(os.listdir(agents_dir)):
        if not filename.endswith(".md"):
            continue
        meta = frontmatter(read(os.path.join(agents_dir, filename)))
        rows.append("| [%s](../agents/%s) | %s | %s |" % (
            meta.get("name", filename[:-3]), filename,
            meta.get("model", ""),
            escape_cell(first_sentence(meta.get("description", "")))))
    write("reference/agents.md", page(
        "Agents", "Subagent definitions installed by setup.sh; they carry "
        "the model-tier routing (see the model-tiering article).",
        "| Agent | Model | Description |", rows))


def build_specs():
    rows = []
    specs_dir = os.path.join(ROOT, "openspec", "specs")
    for filename in sorted(os.listdir(specs_dir)):
        if not filename.endswith(".md"):
            continue
        text = read(os.path.join(specs_dir, filename))
        title = first_h1(text) or filename
        title = re.sub(r"^Spec:\s*", "", title)
        description = ""
        match = re.search(r"## Description\n+((?:[^\n]+\n)+)", text)
        if match:
            description = " ".join(match.group(1).split())
        rows.append("| [%s](../openspec/specs/%s) | %s |" % (
            escape_cell(title), filename,
            escape_cell(first_sentence(description))))
    write("reference/specs.md", page(
        "Specs", "The spec canon (`openspec/specs/`): the normative "
        "requirements every skill, script, and template surface must "
        "agree with (`check_canon.py` enforces the agreement).",
        "| Spec | Description |", rows))


def build_articles():
    rows = []
    docs_dir = os.path.join(ROOT, "docs")
    for filename in sorted(os.listdir(docs_dir)):
        if not filename.endswith(".md"):
            continue
        title = first_h1(read(os.path.join(docs_dir, filename))) or filename
        rows.append("| [%s](../docs/%s) |" % (escape_cell(title), filename))
    write("reference/articles.md", page(
        "Articles", "Guides and workflow documentation from `docs/`.",
        "| Article |", rows))


def build_home():
    write("index.md", GENERATED_NOTE + "\n\n" + read(
        os.path.join(ROOT, "README.md")))


def main():
    build_home()
    build_skills()
    build_agents()
    build_specs()
    build_articles()
    return 0


if __name__ == "__main__":
    sys.exit(main())
